#!/bin/sh

set -e

host="$(hostname -i 2>/dev/null | awk '{print $1}')"
[ -z "$host" ] && host='127.0.0.1'

if mongosh --quiet --host "$host" --eval "var res=db.runCommand({ ping: 1 }); if (res && res.ok===1) { quit(0); } else { quit(2); }"; then
    exit 0
fi

exit 1
